config/routes.rb
Mira::Application.routes.draw do
  root :to => 'home#index'

  resources :items
  put "hide_item" => "items#hide", :as => "hide_item"

  resources :lists
  put "hide_list" => "lists#hide", :as => "hide_list"

  resources :users
  get "users/new"
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  
  resources :sessions
  get "sessions/new"
  
  #get "home/index"
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :list, :include => :user
  
  attr_accessible :content, :visible, :list_id
end

app/models/list.rb
class List < ActiveRecord::Base
  has_many :items, :dependent  => :destroy
  belongs_to :user
  
  attr_accessible :name, :visible
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :lists, :dependent  => :destroy
  
  authenticates_with_sorcery!
  
  
  attr_accessible :email, :password

  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  def not_authenticated
    redirect_to login_url, :alert => "First login to access this page."
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_filter :require_login
  # GET /items
  # GET /items.json
  def index
    @items = Item.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @items }
    end
  end

  # GET /items/1
  # GET /items/1.json
  def show
    #@item = Item.find(params[:id])
    #@item = Item.find(params[:id]) if Item.find(params[:id]).list.user == current_user
    if params[:id].blank?
      @item
    else
      @item ||= current_user.lists.find(Item.find(params[:id]).list.id).items.find(params[:id])
    end
    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @item }
    end
  end

  # GET /items/new
  # GET /items/new.json
  def new
    @item = Item.new(:list_id => params[:list_id])

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @item }
    end
  end

  # GET /items/1/edit
  def edit
    @item = Item.find(params[:id])
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(params[:item])

    respond_to do |format|
      if @item.save
        format.html { redirect_to lists_path, :notice => 'Item was successfully created.' }
        format.json { render :json => lists_path, :status => :created, :location => lists_path }
      else
        format.html { render :action => "new" }
        format.json { render :json => @item.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /items/1
  # PUT /items/1.json
  def update
    @item = Item.find(params[:id])

    respond_to do |format|
      if @item.update_attributes(params[:item])
        format.html { redirect_to lists_path, :notice => 'Item was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @item.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item = Item.find(params[:id])
    @item.destroy

    respond_to do |format|
      format.html { redirect_to lists_url }
      format.json { head :ok }
    end
  end
  
  def hide
    @item = Item.find(params[:id])
    @item.update_attributes(:visible => false)

    respond_to do |format|
      format.html { redirect_to lists_url, :notice => "Item destoyed.#{undo_item_destroing}"} 
      format.json { head :ok }
    end
  end
  
  private
  
  def undo_item_destroing
    view_context.link_to "Undo", item_path(params[:id], :item => {:visible => true}), :method => :put
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_filter :require_login
  # GET /lists
  # GET /lists.json
  def index
    @lists = List.find_all_by_user_id(current_user)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @lists }
    end
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
    #@list = List.find(params[:id])
    @list ||= current_user.lists.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @list }
    end
  end

  # GET /lists/new
  # GET /lists/new.json
  def new
    @list ||= current_user.lists.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @list }
    end
  end

  # GET /lists/1/edit
  def edit
    @list ||= current_user.lists.find(params[:id])
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = User.find(current_user).lists.new(params[:list])

    respond_to do |format|
      if @list.save
        format.html { redirect_to lists_path, :notice => 'List was successfully created.' }
        format.json { render :json => lists_path, :status => :created, :location => lists_path }
      else
        format.html { render :action => "new" }
        format.json { render :json => @list.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /lists/1
  # PUT /lists/1.json
  def update
    @list ||= current_user.lists.find(params[:id])

    respond_to do |format|
      if @list.update_attributes(params[:list])
        format.html { redirect_to lists_path, :notice => 'List was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @list.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list ||= current_user.lists.find(params[:id])
    @list.destroy

    respond_to do |format|
      format.html { redirect_to lists_url, :notice => "Destoyed" }
      format.json { head :ok }
    end
  end
  
  def hide
    @list ||= current_user.lists.find(params[:id])
    @list.update_attributes(:visible => false)

    respond_to do |format|
      format.html { redirect_to lists_url, :notice => "Destoyed.#{undo_list_destroing}"} 
      format.json { head :ok }
    end
  end
  
  private
  
  def undo_list_destroing
    view_context.link_to "Undo", list_path(params[:id], :list => {:visible => true}), :method => :put
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = login(params[:email], params[:password], :remember_me => true)
    if user
      redirect_back_or_to root_url, :notice => "Logged in!"
    else
      if user_exist?(params[:email])
        flash.now.alert = "Password  was invalid"
      else
        flash.now.alert = "Email was invalid"
      end
      render :new
    end
  end
  
  def destroy
    logout
    redirect_to root_url, :notice => "Logged out!"
  end
  
  private
  
  def user_exist?(email)
    !User.where(:email => email).blank?
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
      auto_login(@user)
      redirect_to root_url, :notice => "Signed up!"
    else
      render :new
    end
  end
  
  private
  
  def auto_login(user)
    session[:user_id] = user.id
    @current_user = user
  end

end

app/controllers/versions_controller.rb
class VersionsController < ApplicationController
  def revert
    @version = Version.find(params[:id])
    @version.reify.save!
    redirect_to :back, :notice => "Undid #{@version.event}."
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/versions_helper.rb
module VersionsHelper
end

app/views/home/index.html.haml
%h1 Home page
=link_to 'Your lists', lists_path

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_field :content %>
  </div>
  
  <%= f.hidden_field :list_id %>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<h1>Listing items</h1>

<table>
  <tr>
    <th>Content</th>
    <th>List</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @items.each do |item| %>
  <tr>
    <td><%= item.content %></td>
    <td><%= item.list_id %></td>
    <td><%= link_to 'Show', item %></td>
    <td><%= link_to 'Edit', edit_item_path(item) %></td>
    <td><%= link_to 'Destroy', item, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Item', new_item_path %>

app/views/items/new.html.erb
<h1>New item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Content:</b>
  <%= @item.content %>
</p>

<p>
  <b>List:</b>
  <%= @item.list_id %>
</p>


<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mira</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if current_user %>
  Logged in as <%= current_user.email %>.
  <%= link_to "Log out", logout_path %>
<% else %>
  <%= link_to "Sign up", signup_path %> or
  <%= link_to "log in", login_path %>.
<% end %>
<% flash.each do|name, msg| %>
<%= content_tag :div, raw(msg), :id => "flash_#{name}"%>
<% end %>
<%= yield %>

</body>
</html>

app/views/lists/_form.html.erb
<%= form_for(@list) do |f| %>
  <% if @list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
      <% @list.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lists/edit.html.erb
<h1>Editing list</h1>

<%= render 'form' %>

<%= link_to 'Show', @list %> |
<%= link_to 'Back', lists_path %>

app/views/lists/index.html.haml
=link_to 'Home', root_path
%h1 My lists

%ul
  -@lists.each do |list|
    -if list.visible
      %li
        %h2= list.name
        = link_to 'Edit', edit_list_path(list)
        = link_to 'Destroy', hide_list_path(:id => list), :method => :put
        -if list.items
          %ul
            -list.items.each do |item|
              -if item.visible
                %li
                  = item.content 
                  = link_to 'Edit', edit_item_path(item)
                  = link_to 'Destroy', hide_item_path(:id => item), :method => :put
               
            .list_links 
              = link_to 'New Item', new_item_path(:list_id => list)   
  %br
  = link_to 'New List', new_list_path

app/views/lists/new.html.erb
<h1>New list</h1>

<%= render 'form' %>

<%= link_to 'Back', lists_path %>

app/views/lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @list.name %>
</p>


<%= link_to 'Edit', edit_list_path(@list) %> |
<%= link_to 'Back', lists_path %>

app/views/users/new.html.erb
<h1>Users up</h1>
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %>
    <%= f.text_field :password %>
  </div>
  <div class="actions"><%= f.submit %></div>
<% end %>